import 'server-only'

import fs from 'node:fs/promises'
import path from 'node:path'

import z from 'zod'

/**
 * A project declares what it publishes in a manifest at its root,
 * whose top level maps each artefact kind to that kind's configuration:
 *
 * ```json
 * {
 *   "verso": { "genre": "manual", "exe": "generate-book" }
 * }
 * ```
 *
 * One project may declare several artefacts.
 * A key naming no {@link ArtefactKind} registered here is ignored rather than rejected,
 * since a project may be shared with a workbench that knows more kinds than this one.
 */
export const PUBLISH_MANIFEST_FILE = 'workbench-publish.json'

/** How to build one kind of publishable artefact. */
export interface ArtefactKind<Config = unknown> {
  /** Key under which this kind appears in {@link PUBLISH_MANIFEST_FILE}. */
  readonly id: string
  readonly displayName: string
  /** Validates this kind's entry in the manifest. */
  readonly zConfig: z.ZodType<Config>
  /** How to build an artefact declared by this config. */
  plan(config: Config): BuildPlan
  /** One-line summary of the declared artefact, shown to the project's owner. */
  describe(config: Config): string
}

export interface BuildPlan {
  /** Script under `scripts/`, run inside the sandbox with the project as its cwd.
   * Receives the staging directory as `$1`. */
  script: string
  /** Further arguments, after the staging directory. */
  args: string[]
  /** Directory, relative to the staging directory, that becomes the published site. */
  siteDir: string
}

/**
 * Lake target names are Lean names.
 * We accept a conservative subset of them,
 * chosen to exclude path separators, whitespace, and shell metacharacters
 * so that a manifest cannot smuggle either into the build command.
 */
const LAKE_TARGET_RE = /^[A-Za-z0-9_][A-Za-z0-9_'.-]*$/

const zVersoConfig = z.object({
  /** The Verso document type, which decides where the generator writes the site. */
  genre: z.enum(['manual', 'blog']),
  /** Lake executable target that generates the document. */
  exe: z.string().regex(LAKE_TARGET_RE, 'Invalid Lake target name'),
})

const versoKind: ArtefactKind<z.infer<typeof zVersoConfig>> = {
  id: 'verso',
  displayName: 'Verso document',
  zConfig: zVersoConfig,
  plan: config => ({
    script: 'publish-verso.sh',
    args: [config.exe],
    siteDir: config.genre === 'manual' ? 'html-multi' : '.',
  }),
  describe: config => `Verso ${config.genre}, generated by the Lake target '${config.exe}'`,
}

export const ARTEFACT_KINDS: readonly ArtefactKind[] = [versoKind]

/** An artefact kind the project's manifest declares,
 * either ready to build or with the reason its entry cannot be used. */
export type DetectedArtefact = {
  /** Manifest key of the declaring {@link ArtefactKind}. */
  id: string
  displayName: string
} & ({ plan: BuildPlan; description: string } | { error: string })

/** What a project's manifest says it publishes. */
export type PublishManifest =
  { type: 'missing' } | { type: 'invalid'; error: string } | { type: 'declared'; artefacts: DetectedArtefact[] }

const zManifest = z.record(z.string(), z.unknown())

/** Read `<projectDir>/workbench-publish.json` and resolve the artefacts it declares.
 *
 * A manifest the owner can fix is reported rather than thrown,
 * both when the file as a whole is unusable
 * and when one kind's entry is. */
export async function detectPublishable(projectDir: string): Promise<PublishManifest> {
  let text: string
  try {
    text = await fs.readFile(path.join(projectDir, PUBLISH_MANIFEST_FILE), 'utf-8')
  } catch {
    return { type: 'missing' }
  }

  let json: unknown
  try {
    json = JSON.parse(text)
  } catch (e) {
    return { type: 'invalid', error: `${PUBLISH_MANIFEST_FILE} is not valid JSON: ${String(e)}` }
  }

  const manifest = zManifest.safeParse(json)
  if (!manifest.success) {
    return {
      type: 'invalid',
      error: `${PUBLISH_MANIFEST_FILE} must hold a JSON object mapping artefact kinds to their configuration`,
    }
  }

  return {
    type: 'declared',
    artefacts: ARTEFACT_KINDS.filter(kind => kind.id in manifest.data).map(kind =>
      detectArtefact(kind, manifest.data[kind.id]),
    ),
  }
}

function detectArtefact(kind: ArtefactKind, entry: unknown): DetectedArtefact {
  const { id, displayName } = kind
  const config = kind.zConfig.safeParse(entry)
  if (!config.success) {
    const complaints = config.error.issues.map(issue => describeIssue(id, entry, issue))
    return { id, displayName, error: `${PUBLISH_MANIFEST_FILE} is ill-formed. ${complaints.join('; ')}` }
  }
  return { id, displayName, plan: kind.plan(config.data), description: kind.describe(config.data) }
}

/** Say what is wrong with one entry and where, in terms of the file the author wrote.
 * Zod's own messages name neither the manifest nor the offending value's location. */
function describeIssue(kindId: string, entry: unknown, issue: z.core.$ZodIssue): string {
  const path = [kindId, ...issue.path].map(seg => (typeof seg === 'number' ? `[${seg}]` : `.${String(seg)}`)).join('')
  const where = `in JSON path \`${path}\``
  const found = valueAt(entry, issue.path)
  switch (issue.code) {
    case 'invalid_type':
      return `Expected ${issue.expected}, found ${describeValue(found)} ${where}`
    case 'invalid_value':
      return `Expected one of ${issue.values.map(v => JSON.stringify(v)).join(', ')}, found ${JSON.stringify(found)} ${where}`
    default:
      return `${issue.message} ${where}`
  }
}

/** Name a JSON value by its type, as the manifest's author would think of it. */
function describeValue(value: unknown): string {
  if (value === null) return 'null'
  if (Array.isArray(value)) return 'array'
  return typeof value
}

function valueAt(root: unknown, path: readonly PropertyKey[]): unknown {
  let value = root
  for (const segment of path) {
    if (typeof value !== 'object' || value === null) return undefined
    value = (value as Record<PropertyKey, unknown>)[segment]
  }
  return value
}
