import 'server-only'

import fs from 'node:fs/promises'
import path from 'node:path'

import { describeValue, LAKE_TARGET_RE, valueAt } from '@leanprover/workbench-shared'
import z from 'zod'

/**
 * A project declares what it publishes in a manifest at its root,
 * whose top level maps each artifact kind to that kind's configuration:
 *
 * ```json
 * {
 *   "verso": { "genre": "manual", "exe": "generate-book" }
 * }
 * ```
 *
 * One project may declare several artifacts.
 * A key naming no {@link ArtifactKind} registered here is ignored rather than rejected,
 * since a project may be shared with a workbench that knows more kinds than this one.
 */
export const PUBLISH_MANIFEST_FILE = 'workbench-publish.json'

/** How to build one kind of publishable artifact. */
export interface ArtifactKind<Config = unknown> {
  /** Key under which this kind appears in {@link PUBLISH_MANIFEST_FILE}. */
  readonly id: string
  readonly displayName: string
  /** Validates this kind's entry in the manifest. */
  readonly zConfig: z.ZodType<Config>
  /** How to build an artifact declared by this config. */
  plan(config: Config): BuildPlan
  /** One-line summary of the declared artifact, shown to the project's owner. */
  describe(config: Config): string
}

export interface BuildPlan {
  /** Script under `scripts/`, run inside the sandbox with the project as its cwd.
   * Receives the staging directory as `$1`. */
  script: string
  /** Further arguments, after the staging directory. */
  args: string[]
  /** Directory, relative to the staging directory, that becomes the published site. */
  siteDir: string
}

const zVersoConfig = z.object({
  /** The Verso document type, which decides where the generator writes the site. */
  genre: z.enum(['manual', 'blog']),
  /** Lake executable target that generates the document. */
  exe: z.string().regex(LAKE_TARGET_RE, 'Invalid Lake target name'),
})

const versoKind: ArtifactKind<z.infer<typeof zVersoConfig>> = {
  id: 'verso',
  displayName: 'Verso document',
  zConfig: zVersoConfig,
  plan: config => ({
    script: 'publish-verso.sh',
    args: [config.exe],
    siteDir: config.genre === 'manual' ? 'html-multi' : '.',
  }),
  describe: config => `Verso ${config.genre}, generated by the Lake target '${config.exe}'`,
}

export const ARTIFACT_KINDS: readonly ArtifactKind[] = [versoKind]

/** An artifact kind the project's manifest declares,
 * either ready to build or with the reason its entry cannot be used. */
export type DetectedArtifact = {
  /** Manifest key of the declaring {@link ArtifactKind}. */
  id: string
  displayName: string
} & ({ plan: BuildPlan; description: string } | { error: string })

/** What a project's manifest says it publishes. */
export type PublishManifest =
  { type: 'missing' } | { type: 'invalid'; error: string } | { type: 'declared'; artifacts: DetectedArtifact[] }

const zManifest = z.record(z.string(), z.unknown())

function publishManifestPath(projectDir: string): string {
  return path.join(projectDir, PUBLISH_MANIFEST_FILE)
}

/** A manifest is a short hand-written file. */
const MAX_MANIFEST_BYTES = 64 * 1024

/** The manifest's text, or why the project has none this can use. */
type ManifestFile = { type: 'missing' } | { type: 'invalid'; error: string } | { type: 'read'; text: string }

/**
 * Read the project's manifest.
 *
 * The project directory is writable from its owner's sandbox, but this runs unsandboxed,
 * so the file is opened without following a final symlink
 * and is read only once it is known to be an ordinary file of plausible size.
 * `O_NONBLOCK` keeps the open itself from waiting, which it otherwise would on a FIFO.
 */
async function readPublishManifest(projectDir: string): Promise<ManifestFile> {
  const manifestPath = publishManifestPath(projectDir)
  const mustBe = (what: string): ManifestFile => ({
    type: 'invalid',
    error: `${PUBLISH_MANIFEST_FILE} must be ${what}.`,
  })

  const flags = fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW | fs.constants.O_NONBLOCK
  const handle = await fs.open(manifestPath, flags).catch(() => undefined)
  if (!handle) {
    // `O_NOFOLLOW` fails with ELOOP on a symbolic link,
    // so an entry that is still there is one we declined to open rather than one that is absent.
    if (await fs.lstat(manifestPath).catch(() => undefined)) return mustBe('an ordinary file, not a symbolic link')
    return { type: 'missing' }
  }
  try {
    const stat = await handle.stat()
    if (!stat.isFile()) return mustBe('an ordinary file')
    if (stat.size > MAX_MANIFEST_BYTES) return mustBe(`smaller than ${MAX_MANIFEST_BYTES} bytes`)
    return { type: 'read', text: await handle.readFile('utf-8') }
  } finally {
    await handle.close()
  }
}

/** Whether the project declares a manifest at all.
 * A project without one has no publishing interface,
 * so this gates both the project list's publish link and the publish page itself.
 *
 * Anything occupying the name counts, including something {@link readPublishManifest} refuses to read,
 * so that the owner reaches the page that says what is wrong with it. */
export async function hasPublishManifest(projectDir: string): Promise<boolean> {
  return !!(await fs.lstat(publishManifestPath(projectDir)).catch(() => undefined))
}

/** Read `<projectDir>/workbench-publish.json` and resolve the artifacts it declares.
 *
 * A manifest the owner can fix is reported rather than thrown,
 * both when the file as a whole is unusable
 * and when one kind's entry is. */
export async function detectPublishable(projectDir: string): Promise<PublishManifest> {
  const file = await readPublishManifest(projectDir)
  if (file.type !== 'read') return file

  let json: unknown
  try {
    json = JSON.parse(file.text)
  } catch (e) {
    return { type: 'invalid', error: `${PUBLISH_MANIFEST_FILE} is not valid JSON: ${String(e)}` }
  }

  const manifest = zManifest.safeParse(json)
  if (!manifest.success) {
    return {
      type: 'invalid',
      error: `${PUBLISH_MANIFEST_FILE} must hold a JSON object mapping artifact kinds to their configuration`,
    }
  }

  return {
    type: 'declared',
    artifacts: ARTIFACT_KINDS.filter(kind => kind.id in manifest.data).map(kind =>
      detectArtifact(kind, manifest.data[kind.id]),
    ),
  }
}

function detectArtifact(kind: ArtifactKind, entry: unknown): DetectedArtifact {
  const { id, displayName } = kind
  const config = kind.zConfig.safeParse(entry)
  if (!config.success) {
    const complaints = config.error.issues.map(issue => describeIssue(id, entry, issue))
    return { id, displayName, error: `${PUBLISH_MANIFEST_FILE} is ill-formed. ${complaints.join('; ')}` }
  }
  return { id, displayName, plan: kind.plan(config.data), description: kind.describe(config.data) }
}

/** Say what is wrong with one entry and where, in terms of the file the author wrote.
 * Zod's own messages name neither the manifest nor the offending value's location. */
function describeIssue(kindId: string, entry: unknown, issue: z.core.$ZodIssue): string {
  const path = [kindId, ...issue.path].map(seg => (typeof seg === 'number' ? `[${seg}]` : `.${String(seg)}`)).join('')
  const where = `in JSON path \`${path}\``
  const found = valueAt(entry, issue.path)
  switch (issue.code) {
    case 'invalid_type':
      return `Expected ${issue.expected}, found ${describeValue(found)} ${where}`
    case 'invalid_value':
      return `Expected one of ${issue.values.map(v => JSON.stringify(v)).join(', ')}, found ${JSON.stringify(found)} ${where}`
    default:
      return `${issue.message} ${where}`
  }
}
