'use client'

import { useState } from 'react'
import z from 'zod'

import authClient from '@/lib/client/auth'

export default function Unauthorized() {
  const [oneTimePassword, setOneTimePassword] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [confirmNewPassword, setConfirmNewPassword] = useState('')

  const [status, setStatus] = useState<
    null | { type: 'incorrect-password' } | { type: 'api-error'; message: string } | { type: 'no-match' }
  >(null)

  /** Updates status after the password or password confirmation changes */
  function checkMatch(password: string, confirm: string) {
    if (password.trim() === '' || confirm.trim() === '' || password === confirm) {
      setStatus(null)
    } else {
      setStatus({ type: 'no-match' })
    }
  }
  async function login() {
    try {
      await authClient.signIn.email({
        email: 'admin@admin.localhost',
        password: oneTimePassword,
      })

      // This try-catch won't perfectly prevent a bypass of the change-password
      // requirement, but it's about the best we can do client-side
      try {
        await authClient.changePassword({ currentPassword: oneTimePassword, newPassword })
      } catch (e) {
        await authClient.signOut()
        throw e
      }

      // useRouter().refresh() won't clear the unauthorized() status
      window.location.reload()
    } catch (e) {
      if (z.object({ error: z.object({ code: z.literal('INVALID_EMAIL_OR_PASSWORD') }) }).safeParse(e).success) {
        setStatus({ type: 'incorrect-password' })
      } else {
        const betterAuthMessage = z.object({ error: z.object({ message: z.string() }) }).safeParse(e)
        setStatus({
          type: 'api-error',
          message: betterAuthMessage.success
            ? betterAuthMessage.data.error.message
            : e instanceof Error
              ? e.message
              : String(e),
        })
      }
    }
  }

  return (
    <div>
      <h1>Create Admin Account</h1>
      <div style={{ display: 'grid', gap: 8 }}>
        <p>Welcome to Lean Workbench!</p>
        <p>
          To create an administrator account and begin, enter the one-time password generated by <code>install.sh</code>
          .
        </p>
        <form action={login} style={{ display: 'grid', gap: 4 }}>
          <label htmlFor='one-time-password'>
            One-time initialization password
            <input
              data-1p-ignore
              id='one-time-password'
              autoComplete='current-password'
              type='password'
              value={oneTimePassword}
              onChange={e => {
                setOneTimePassword(e.target.value)
                checkMatch(newPassword, confirmNewPassword)
              }}
              required
              style={{ width: '100%', marginTop: 4 }}
            />
          </label>
          {status?.type === 'incorrect-password' && <p style={{ color: '#F00' }}>Incorrect password</p>}
          <label htmlFor='new-password'>
            New admin password
            <input
              id='new-password'
              autoComplete='new-password'
              type='password'
              minLength={8}
              value={newPassword}
              onChange={e => {
                setNewPassword(e.target.value)
                checkMatch(e.target.value, confirmNewPassword)
              }}
              required
              style={{ width: '100%', marginTop: 4 }}
            ></input>
          </label>
          <label htmlFor='confirm-new-password'>
            Confirm new admin password
            <input
              id='confirm-new-password'
              autoComplete='new-password'
              type='password'
              minLength={8}
              value={confirmNewPassword}
              onChange={e => {
                setConfirmNewPassword(e.target.value)
                checkMatch(newPassword, e.target.value)
              }}
              required
              style={{ width: '100%', marginTop: 4 }}
            ></input>
          </label>
          {status?.type === 'no-match' && <p style={{ color: '#F00' }}>New passwords don&apos;t match</p>}
          <button
            type='submit'
            disabled={status !== null || oneTimePassword.trim() === '' || newPassword.trim() === ''}
          >
            Log in
          </button>
          {status?.type === 'api-error' && <p style={{ color: '#F00' }}>{status.message}</p>}
        </form>
      </div>
    </div>
  )
}
